spring:
  application:
    name: learn-graphql-springboot

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 5
  playground:
#    enabled: false
    headers:
      Authorization: Bearer TOKEN_XYZ
    tabs:
      - name: Bank Account Sample Query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
